name: Continuous Delivery Wesley
on:
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4


      - name: Simulando Continous Deliver
        uses: actions/upload-artifact@v4
        with:
          name: projetozipado.zip
          path: |
            main.py
            README.md
